// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/rubiojr/gasdb/_server/translations"

func BrandBanner(t translations.Translations) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg class=\"brand-banner\" viewBox=\"0 0 720 160\" role=\"img\" aria-label=\"GasDB\" xmlns=\"http://www.w3.org/2000/svg\"><g aria-hidden=\"true\"><path class=\"brand-road\" pathLength=\"1\" d=\"M510 24C558 24 586 32 586 58C586 92 544 98 575 118C601 137 649 136 689 136\" fill=\"none\" stroke=\"var(--brand-road)\" stroke-width=\"42\" stroke-linecap=\"round\"></path> <path class=\"brand-lane\" d=\"M510 24C558 24 586 32 586 58C586 92 544 98 575 118C601 137 649 136 689 136\" fill=\"none\" stroke=\"var(--green)\" stroke-width=\"2\" stroke-dasharray=\"10 13\" opacity=\".65\"></path> <circle class=\"brand-waypoint-halo\" cx=\"569\" cy=\"93\" r=\"23\" fill=\"var(--green)\" opacity=\".14\"></circle> <circle cx=\"569\" cy=\"93\" r=\"10\" fill=\"var(--green)\"></circle> <circle cx=\"569\" cy=\"93\" r=\"3\" fill=\"var(--page-bg)\"></circle></g> <text x=\"4\" y=\"20\" class=\"brand-kicker\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(t.BrandEyebrow)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `brand.templ`, Line: 14, Col: 58}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</text> <text x=\"0\" y=\"124\" class=\"brand-wordmark\" fill=\"var(--text-dark)\">Gas<tspan fill=\"var(--green)\">DB</tspan></text></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
